server:
  port: 8888
  tomcat:
    connection-timeout: -1
spring:
  security:
    user:
      name: admin
      password: admin11234
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin1123
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB
upload:
  file:
    timeout: 48  #文件显示过期时间(单位:小时)
  target:
    folder: /usr/data/

logging:
  level:
    com.tdp.data.web.service.DbMapper: debug

